dist:     xenial
sudo:     false
language: go
env:
  - TF_LOG=debug TF_ACC=true TAGS="acceptance"
go:
  - 1.11.x
  - 1.12.x
git:
  depth: 1
  go_import_path: github.com/stbenjam/git-clone-fork
  install: true
  script:
    - make fmt
    - make lint
    - make vet
    - make build
