name: Tests
on: pull_request
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Run golang-ci
        uses: actions-contrib/golangci-lint@v0.1.0

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Setup environment
        run: |
          export GOFLAGS="-mod=vendor"

      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Run Unit Tests
        run: go test -v -race ./...

      - name: Build
        run: go build .

      - name: Checkout test repo
        run: ./git-clone-fork -h stbenjam/testrepo

      - name: Verify repo has upstream remote
        run: |
          cd testrepo
          (git ls-remote --get-url origin | grep -q https://github.com/stbenjam/testrepo.git) || exit 1
          (git ls-remote --get-url upstream | grep -q https://github.com/github/testrepo.git) || exit 1
